language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -r requirements.txt -r requirements-dev.txt"
# command to run tests
script: coverage3 run --source acceptable --omit "acceptable/tests/*" setup.py test
after_success:
  - coveralls
matrix:
  allow_failures:
    - "nightly"
