language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt -r requirements-dev.txt"
# command to run tests
script: coverage3 run --source acceptable --omit "acceptable/tests/*" setup.py test
after_success:
  - coveralls
