language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt -r requirements-dev.txt"
# command to run tests
script: coverage run --source acceptable --omit "acceptable/tests/*" setup.py test
after_success:
  - coveralls
